### ISSUE TITLE
E

### ISSUE THREAD

**Issue by rounk-ctrl** [Endeade/DatShell#1]
Error
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at DatShell.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ContainerControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

Time
![image](https://user-images.githubusercontent.com/70931017/216785580-1ffe2410-79c7-4ed7-9618-5a2079f73861.png)

welcomeString
![image](https://user-images.githubusercontent.com/70931017/216785639-69eed1f2-1c84-47a9-af35-b0e450576dcb.png)

Taskbar appears in alt+Tab
u can alt f4 taskbar

Os
window 10 1607 ltsb

**Comment by kiiatto** [comment]
why are you using windows 10 1607
that's a very old version of windows 10
w h y

**Comment by rounk-ctrl** [comment]
because it best

**Comment by kiiatto** [comment]
no it's not
if you want to use an old version of windows, use windows 7
it's the best if you want to run an os even semi-compatible with stuff

**Comment by Noctade** [comment]
will look into it

**Comment by rounk-ctrl** [comment]
But i cant install windows 7 😭

**Comment by WindowsShadows** [comment]
> no it's not if you want to use an old version of windows, use windows 7 it's the best if you want to run an os even semi-compatible with stuff

Go poop in a sewer

**Comment by legofanlovessayori** [comment]
> > no it's not if you want to use an old version of windows, use windows 7 it's the best if you want to run an os even semi-compatible with stuff
> 
> Go poop in a sewer

help me i shat into my toilet, i now have cock in my ass

**Comment by Endeade** [comment]
> > > no it's not if you want to use an old version of windows, use windows 7 it's the best if you want to run an os even semi-compatible with stuff
> > 
> > 
> > Go poop in a sewer
> 
> help me i shat into my toilet, i now have cock in my ass

HOW DOES THAT HAPPEN?!?!

**Comment by legofanlovessayori** [comment]
> > > > no it's not if you want to use an old version of windows, use windows 7 it's the best if you want to run an os even semi-compatible with stuff
> > > 
> > > 
> > > Go poop in a sewer
> > 
> > 
> > help me i shat into my toilet, i now have cock in my ass
> 
> HOW DOES THAT HAPPEN?!?!

HELP ME I NOW HAVE RECTUM DAMAGE

**Comment by WindowsShadows** [comment]
> > > > > no it's not if you want to use an old version of windows, use windows 7 it's the best if you want to run an os even semi-compatible with stuff
> > > > 
> > > > 
> > > > Go poop in a sewer
> > > 
> > > 
> > > help me i shat into my toilet, i now have cock in my ass
> > 
> > 
> > HOW DOES THAT HAPPEN?!?!
> 
> HELP ME I NOW HAVE RECTUM DAMAGE

buy a ddlc plushie, should fix it

**Comment by Endeade** [comment]
yall do realize that commenting on this is spamming on the git channel in the server?

**Comment by legofanlovessayori** [comment]
TIME TO SHIT ALL OVER IT WOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by WindowsShadows** [comment]
> yall do realize that commenting on this is spamming on the git channel in the server?
The KITi will climb a tree, for better signal

**Comment by WindowsShadows** [comment]
> yall do realize that commenting on this is spamming on the git channel in the server?

The KITi will climb a tree, for better signal

**Comment by GitCat42** [comment]
this is a message

**Comment by Endeade** [comment]
THIS IS NOT IRC FOR THE GIT CHANNEL LMFAO

**Comment by GitCat42** [comment]
LMFAO

**Comment by GitCat42** [comment]
[cat](cat.cat)

**Comment by legofanlovessayori** [comment]
very cock

**Comment by GitCat42** [comment]
much

**Comment by WindowsShadows** [comment]
Flame broiled ass clown

**Comment by GitCat42** [comment]
![Screenshot 2023-02-05 8 13 30 AM](https://user-images.githubusercontent.com/119998752/216786336-e7e6b03b-0473-4558-ad63-f69f24cfd8e5.png)

**Comment by GitCat42** [comment]
this is my desktop

**Comment by WindowsShadows** [comment]
![image](https://user-images.githubusercontent.com/68105821/216786355-1da15171-9318-484d-b2ea-83cd406c2841.png)

**Comment by legofanlovessayori** [comment]
lets just blow our toilets up, with liquid shit

**Comment by WindowsShadows** [comment]
this is my desktop

**Comment by GitCat42** [comment]
> ![image](https://user-images.githubusercontent.com/68105821/216786355-1da15171-9318-484d-b2ea-83cd406c2841.png)

yours is way better

**Comment by WindowsShadows** [comment]
> lets just blow our toilets up, with liquid shit

ima flush a couple ppl in my toilet brb

**Comment by GitCat42** [comment]
this has turned from a github issue into a mini discord server

**Comment by kiiatto** [comment]
> But i cant install windows 7 😭

you don't have to install an oem version

**Comment by Noctade** [comment]
THIS IS NOT R/TECHSUPPORT

**Comment by dky4** [comment]
> THIS IS NOT R/TECHSUPPORT

YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT

**Comment by Noctade** [comment]
bruh

**Comment by legofanlovessayori** [comment]
> > THIS IS NOT R/TECHSUPPORT
> 
> YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT

help my penis won't go down

**Comment by GitCat42** [comment]
> > > THIS IS NOT R/TECHSUPPORT
> > 
> > 
> > YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT
> 
> help my penis won't go down

look at something ugly

**Comment by WindowsShadows** [comment]
> > > THIS IS NOT R/TECHSUPPORT
> > 
> > 
> > YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT
> 
> help my penis won't go down

eat 60 tonnes of viagra

**Comment by WindowsShadows** [comment]
it'll go so high it'll break off and yeah

**Comment by GitCat42** [comment]
> > > > THIS IS NOT R/TECHSUPPORT
> > > 
> > > 
> > > YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT
> > 
> > 
> > help my penis won't go down
> 
> look at something ugly

^

**Comment by legofanlovessayori** [comment]
> it'll go so high it'll break off and yeah

i am pretty sure that jevil will likes that

**Comment by legofanlovessayori** [comment]
STOP SAYING JITHUB YOU EEEEEEEEEEEE

**Comment by WindowsShadows** [comment]
> > > > > THIS IS NOT R/TECHSUPPORT
> > > > 
> > > > 
> > > > YOU'RE RIGHT, THIS IS R/ERECTIONSUPPORT
> > > 
> > > 
> > > help my penis won't go down
> > 
> > 
> > look at something ugly
> 
> ^

no, it won't work, he's too addicted to DDLC which is already ugly

**Comment by GitCat42** [comment]
oh

**Comment by GitCat42** [comment]
ok then

**Comment by legofanlovessayori** [comment]
ITS GITHUB NOT JITHUB YOU AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by WindowsShadows** [comment]
i'm going to subtitle a vid i saw in 2020:
VICTORY SCREECH!!!!!!!!!!!!!!!!!!!
*man cuts off his dick*
Da end
(no joke someone tricked me into watching that lmao)

**Comment by Jevil7452** [comment]
> > it'll go so high it'll break off and yeah
> 
> i am pretty sure that jevil will likes that

Yay

**Comment by Endeade** [comment]
> > > it'll go so high it'll break off and yeah
> > 
> > 
> > i am pretty sure that jevil will likes that
> 
> Yay

AHAHAHAAHAAHAHHAAh

**Comment by legofanlovessayori** [comment]
simple as that

**Comment by WindowsShadows** [comment]
> it'll go so high it'll break off and yeah

it works, i did it myself

**Comment by WindowsShadows** [comment]
other people editing should not be allowed.

**Comment by GitCat42** [comment]
okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails

**Comment by legofanlovessayori** [comment]
> okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails

its fun tho

**Comment by WindowsShadows** [comment]
Flame broiled ass clown message underneath

> okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails

**Comment by legofanlovessayori** [comment]
CUM

**Comment by WindowsShadows** [comment]
help my dick came back, any good methods of cutting it off?

**Comment by Jevil7452** [comment]
> okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails

I got just the fix for you
![image](https://user-images.githubusercontent.com/98893064/216786891-d5c535e7-80a0-4461-af41-6e0143a6f6a9.png)

**Comment by ImSwordKing** [comment]
god

**Comment by legofanlovessayori** [comment]
> 

send it to heaven

**Comment by legofanlovessayori** [comment]
cum here you E

**Comment by WindowsShadows** [comment]
Poo po

**Comment by ImSwordKing** [comment]
same issue, please delete èprogranmme

**Comment by WindowsShadows** [comment]
ok i think we should stop or my brain iq will go beyond -9

**Comment by WindowsShadows** [comment]
(which is what it's currently at)

**Comment by megamanyoutuber** [comment]
lego you have a shitty wife reisen is a better wife

**Comment by legofanlovessayori** [comment]
CUM

**Comment by Endeade** [comment]
the fuck

**Comment by ImSwordKing** [comment]
i love femboyssss xxxxx

**Comment by megamanyoutuber** [comment]
i will the fuck reisen... and you

> the fuck

**Comment by WindowsShadows** [comment]
someone will drink cum here rn i bet

**Comment by legofanlovessayori** [comment]
OH HEY BABE
[SHITS AGRESSIVELY]

**Comment by megamanyoutuber** [comment]
i'm drinking cum from my freezer

**Comment by Endeade** [comment]
okay you're done

**Comment by ricol03** [comment]
no marisa best

**Comment by megamanyoutuber** [comment]
reisen better

**Comment by WindowsShadows** [comment]
no closing this dario

**Comment by ricol03** [comment]
no

**Comment by ImSwordKing** [comment]
Follow @follwcoolpeople om twitter

**Comment by Endeade** [comment]
HOW ARE YOU STILL COMMENTING!?

**Comment by ricol03** [comment]
close it datdot

**Comment by megamanyoutuber** [comment]
you cannot the close

**Comment by legofanlovessayori** [comment]
> HOW ARE YOU STILL COMMENTING!?

cock

**Comment by Endeade** [comment]
haha fuck you all now

**Comment by WindowsShadows** [comment]
HAHA FUCK YOURSELF NOW

**Comment by legofanlovessayori** [comment]
HE HAS BALLS

**Comment by WindowsShadows** [comment]
you mean they?
they are dreamgender and dreamsexual

**Comment by ricol03** [comment]
datmommy has teh big balls uwu

**Comment by megamanyoutuber** [comment]
and i have tt because i am gril

**Comment by Endeade** [comment]
baba gril

**Comment by WindowsShadows** [comment]
@Endeade 
![image](https://user-images.githubusercontent.com/68105821/216787321-f360b40d-6b95-4305-99cc-ba0c47e5f79b.png)

**Comment by legofanlovessayori** [comment]
datdot はおかしな人です。彼は過去に多くのゲイ セックスを行っていました。 彼はお尻に別のペニスができるまで、料理をするのをやめません

**Comment by megamanyoutuber** [comment]
я в-ебу твой писюн

**Comment by ricol03** [comment]
wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by Endeade** [comment]
> wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww

**Comment by megamanyoutuber** [comment]
**fat text**

**Comment by WindowsShadows** [comment]
https://youtu.be/o7OeJwv9weQ ack off to this video pls

**Comment by legofanlovessayori** [comment]
彼は1984年のコミットをやめません。私たちは今、アニメ言語でコミュニケーションしなければなりません. 私たちが興奮するのを手伝ってください

**Comment by legofanlovessayori** [comment]
彼は1984年のコミットをやめません。私たちは今、アニメ言語でコミュニケーションしなければなりません. 私たちが興奮するのを手伝ってください

**Comment by ricol03** [comment]
datdot is a funny person. He has had a lot of gay sex in the past. He won't stop cooking until he has another dick in his ass
translated from sayori-chan

**Comment by legofanlovessayori** [comment]
彼は1984年のコミットをやめません。私たちは今、アニメ言語でコミュニケーションしなければなりません. 私たちが興奮するのを手伝ってください

**Comment by WindowsShadows** [comment]
@legofanlovessayori 
![image](https://user-images.githubusercontent.com/68105821/216787403-e44b63b5-0589-4293-94cc-33620baed01e.png)
pov living in germany

**Comment by ricol03** [comment]
uwu
i love you too datmommy :3

**Comment by legofanlovessayori** [comment]
UWU we love datdaddy :3

**Comment by WindowsShadows** [comment]
oh fuck you censorship datdaddy

**Comment by megamanyoutuber** [comment]
datdot daddy UwU

**Comment by legofanlovessayori** [comment]
datdot にはボールがありません。

**Comment by ricol03** [comment]
censorship AAAAAAAAAAAAAAA

**Comment by ricol03** [comment]
> datdot にはボールがありません。

agreed

**Comment by legofanlovessayori** [comment]
dot said that i do not have brain

**Comment by WindowsShadows** [comment]
i am going to sleep now or e, gn everyone here

**Comment by megamanyoutuber** [comment]
datdot fuck me owo

**Comment by ricol03** [comment]
datdot にはピピがありません

**Comment by ricol03** [comment]
datdot は le dishery をコミットします

**Comment by legofanlovessayori** [comment]
彼は放射能で生きている

**Comment by Endeade** [comment]
imma go sleep stop with hirny

**Comment by ricol03** [comment]
no horny

**Comment by legofanlovessayori** [comment]
> imma go sleep stop with hirny

あなたが私たちが欲求不満であることを受け入れるまでは

**Comment by GitCat42** [comment]
> Flame broiled ass clown message underneath
> 
> > okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails

shut up

**Comment by WindowsShadows** [comment]
> > Flame broiled ass clown message underneath
> > > okay stop commenting on this unless it's a fix to the original problem, i'm getting _way_ too many emails
> 
> shut up

ADOLF HITLER HINDI एडॉल्फ हिटलर

**Comment by Noctade** [comment]
I sadly cannot reproduce the issue but I have made some code optimizations in v0.0.2. If it still does this, try launching the program with Admin permissions and if it still occurs open a new issue.

**Comment by dky4** [comment]
![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png)
actually, get a english grammar book first

**Comment by Noctade** [comment]
> ![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png) actually, get a english grammar book first

Are you perhaps happy now?

**Comment by kiiatto** [comment]
god damn our funny discussion is dead :(
can we get an F in this comment section for our now-dead conversation

**Comment by kiiatto** [comment]
god damn our funny discussion is dead :(
can we get an F in this comment section for our now-dead conversation

**Comment by dky4** [comment]
> > ![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png) actually, get a english grammar book first
> 
> Are you perhaps happy now?

No, no I am not.

**Comment by legofanlovessayori** [comment]
> > > ![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png) actually, get a english grammar book first
> > 
> > Are you perhaps happy now?
> 
> No, no I am not.

why the fuck did it take you 8 months to reply

**Comment by kiiatto** [comment]
> > > > ![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png) actually, get a english grammar book first
> > > 
> > > 
> > > Are you perhaps happy now?
> > 
> > 
> > No, no I am not.
> 
> why the fuck did it take you 8 months to reply

bruhhhhh

**Comment by RocketLauncher21** [comment]
> > > > ![image](https://user-images.githubusercontent.com/68105821/216982917-7f386ce7-92c0-47fd-9d95-3eabca9f96b7.png) actually, get a english grammar book first
> > > 
> > > 
> > > Are you perhaps happy now?
> > 
> > 
> > No, no I am not.
> 
> why the fuck did it take you 8 months to reply

Whether you East Side or West Side of the 313
Let's see them guns blaze
