### ISSUE TITLE
Errore in italiano

### ISSUE THREAD

**Issue by ImSwordKing** [Endeade/DatShell#12]
Il tuo programma non funziona correttamente se la lingua selezionata è "italiano"

Perfavore risolvi questo problema e il problema #7

**Comment by ricol03** [comment]
Mamma mia, sorry, i want to learn italian

**Comment by ImSwordKing** [comment]
Ok understand.

**Comment by Endeade** [comment]
this program is currently not meant to have translations, maybe sometime in the future
