### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by legofanlovessayori** [Endeade/DatShell#13]
p l z  h  alPÜ wiTH mah winow

![image](https://user-images.githubusercontent.com/94994630/216787218-e94d8c7b-c5a8-46d7-ba3e-b640f6834fe3.png)

**Comment by Endeade** [comment]
slmgr /skms kms8.msguides.com
then go to settings and put a random key from https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys that matches your edition
