### ISSUE TITLE
Shell giving an error at startup.

### ISSUE THREAD

**Issue by ImSwordKing** [Endeade/DatShell#2]
The latest version of your shell gives an error at startup on Windows 8.1 build 9600 x64.

The error is "Datmommy.dll can't be found. Please reinstall the program"

I hope this issue will be fixed.

**Comment by legofanlovessayori** [comment]
cmere datmommy nya~

**Comment by ImSwordKing** [comment]
Thank you it worked.

**Comment by Endeade** [comment]
> The latest version of your shell gives an error at startup on Windows 8.1 build 9600 x64.
> 
> The error is "Datmommy.dll can't be found. Please reinstall the program"
> 
> I hope this issue will be fixed.

install .net fx 4.7.2 and run as admin

**Comment by ImSwordKing** [comment]
Installing .net fx 4.0 worked. Thank you
